### ISSUE TITLE
 Unlock all the streets

### ISSUE THREAD

**Issue by SuperFurias** [lynaevm/BreakOut#15]
Once unlocked the "Kappa pick" that serves to unlock only one of the 4 streets, I thought "But I found a book with indestructibility 3 !!" I crafted an anvil, I applied ind 3 to the pick and I managed (I admit that I was lucky) to unlock 2 roads, almost 3 (the third was missing only 1 block to break but broke the pickaxe) Make sure that at the Kappa pick can not be applied enchant otherwise the gameplay is ruined, as I read of these picks you have to get 4, to me it was enough almost only 1

**Comment by Hallowizer** [comment]
I also figured out how to get all streets, but in a different way. Once I unlocked two rooms, I opened an AE room, and I took the Sky Stone. Then, I made a Sticky Piston, and pulled out the Concrete door blocking another AE room. Then, I broke the wiring to make the pistons for room 3 retract, and I made it in.

**Comment by lynaevm** [comment]
Unlocking only one room at a time serves two purposes in the design of this game.  For players who are new to modded, it lets them focus on one new thing at a time instead of being overwhelmed by all the options.  For players who are more experienced, it challenged them to do without some of their favorite tools and think about more unusual ways to solve problems.  Sounds like method #2 worked for you :D
